modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/RobertSkalko/Mine-and-Slash/issues"
[[mods]]
modId="mmorpg"
version="${file.jarVersion}"
displayName="Mine and Slash"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="icon.png" #
credits="Thanks for this example mod goes to Java"
authors="mcrobertx22"
description='''
Turns Minecraft into a hack and slash RPG!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.mmorpg]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mmorpg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mmorpg]]
    modId="divine_missions"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mmorpg]]
    modId="world_of_exile"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mmorpg]]
    modId="library_of_exile"
    mandatory=true
    versionRange="[1.2.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mmorpg]]
    modId="curios"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"